[package]
name = "argon2"
version = "0.2.2"
authors = ["quininer <quininer@live.com>"]
# build = "build.rs"

[dependencies]
libc = "0.2"

[build-dependencies.ffigen]
version = "0.2"
git = "https://github.com/quininer/rust-ffigen.git"
