[package]
name = "argon2"
version = "0.2.2"
authors = ["quininer <quininer@live.com>"]
build = "build.rs"

[dependencies]
libc = "0.2"

[build-dependencies.crustacean]
git = "https://github.com/KyleMayes/crustacean.git"
